theme: jekyll-theme-cayman
title: LocAdoc
author: LocAdoc Team
description: "A UOW final year project S3/2017"

# build settings
port: 4000
highlighter: pygments
markdown: redcarpet
permalink: pretty
